apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-service
spec:
  selector:
    app: elasticsearch
  type: NodePort
  clusterIP: 10.68.108.46
  ports:
  - port: 9300
    name: port-9300
    protocol: TCP
    targetPort: 9300
    nodePort: 30013   
  - port: 9200
    name: port-9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30012
#  externalIPs:
#    - 192.168.127.134

