apiVersion: v1
kind: Service
metadata:
  name: beanstalkd-service
  labels:
    name: beanstalkd
spec:
  selector:
    name: beanstalkd
  ports:
  - port: 8010
    targetPort: 11300
    name: beanstalkd-8010
  externalIPs:
  - 106.14.105.169
