apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beanstalkd  
  labels: 
    name: beanstalkd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: beanstalkd
  template:
    metadata:
      labels:
        name: beanstalkd
    spec:
      containers:
        - name: beanstalkd
          image: schickling/beanstalkd
         # command: ["/bin/sh"]
         # args: ["-f", "/etc/profile"]
          imagePullPolicy: Always
          ports:
            - containerPort: 11300
          volumeMounts:
            - mountPath: /var/lib/beanstalkd
              name: nfsdata
      imagePullSecrets:
        - name: registrykey-1
      volumes:
        - name: nfsdata
          nfs:
            server: 10.29.46.54
            path: /data/nfs/beanstalkd
