apiVersion: v1 
kind: Service 
metadata: 
  name: mysql 
  labels: 
    name: mysql 
spec: 
  externalIPs: 
    - 106.14.105.169 
  ports: 
    - port: 3306 
      targetPort: 3306 
  selector: 
    name: mysql
