#集群名
cluster.name: tj-pro
 
#节点名
node.name: tj-pro-node-47


#设置绑定的ip地址，可以是ipv4或ipv6的，默认为0.0.0.0，
#指绑定这台机器的任何一个ip
network.bind_host: 0.0.0.0

#设置其它节点和该节点交互的ip地址，如果不设置它会自动判断，
#值必须是个真实的ip地址  
network.host: 47.98.34.215


#设置对外服务的http端口，默认为9200
http.port: 9200

#设置节点之间交互的tcp端口，默认是9300
transport.tcp.port: 9300


#是否允许跨域REST请求
http.cors.enabled: true

#允许 REST 请求来自何处
http.cors.allow-origin: "*"


#节点角色设置
#该结点有资格被选举为主结点（候选主结点）
node.master: true
#该结点是数据结点
node.data: true


#有成为主节点资格的节点列表
discovery.zen.ping.unicast.hosts: ["47.98.34.215:9300","47.98.150.93:9300"]
 
#集群中一直正常运行的，有成为master节点资格的最少节点数（默认为1）
# (totalnumber of master-eligible nodes / 2 + 1)
discovery.zen.minimum_master_nodes: 1

xpack.license.self_generated.type: basic
xpack.security.enabled: true
